### ISSUE TITLE
APIC cookie requirement

### ISSUE THREAD

**Issue by Saboom** [rc9000/nd2-worker-plugin-aci#2]
Good afternoon, thank you for writing this Netdisco plugin, I have gotten it to work with our newer 5.x deployment somewhat but have run into some roadblocks I was hoping you could give some insight on.

When querying it is looking for a cookie and not finding it so failing on some things.

"text" : "Need a valid webtoken cookie (named APIC-Cookie) or a signed request with signature in the cookie APIC-Request-Signature for all REST AP
I requests",
               "code" : "403"

Is there anything I can adjust to make it get and use a cookie?

Thank you

**Comment by rc9000** [comment]
Hi! The APIC-Cookie should be obtained automatically from the login() code in these regions of the code: https://github.com/rc9000/nd2-worker-plugin-aci/blob/master/lib/App/NetdiscoX/Util/ACI.pm#L210

It could be that your user/password in device_auth is wrong, or somehow not picked up by netdisco due to wrong only: settings... it should look like this - the ip is the ACI controller

```
device_auth:
  - tag: aci
    driver: netconf
    only:
      - 10.5.199.5 
    user: 'aciuser'
    password: 'topsecret' 
```
Maybe check that? I'll see if we have a 5.x APIC somehere by now and check if it sitll works there for me, it has actually been a while since I last used this plugin.
