### ISSUE TITLE
Possible fix: use rDNS to avoid "certificate verify failed" errors

### ISSUE THREAD

**Issue by sjuerges** [rc9000/nd2-worker-plugin-aci#5]
Hi :)

I noticed something after providing our APICs with corret certificates and setting the correct HTTPS_CA_FILE ENV Variable to use the correct CA. The macsuck/arpnip would STILL fail, because we do not include IP Addresses in the certificates, and the current code will always build the "URL" using the IP address of the APIC node. see: 

https://github.com/rc9000/nd2-worker-plugin-aci/blob/edc02c74fc49061ec39fc72bfd20c90f77974c38/lib/App/NetdiscoX/Util/ACI.pm#L34

I have rewritten this a litttle bit for our purpose, to use rDNS to resolve the hostname to that IP and use THAT to connect, to avoid the otherwise unavoidable certificate error:

```
diff --git a/lib/App/NetdiscoX/Util/ACI.pm b/lib/App/NetdiscoX/Util/ACI.pm
index 15bf3cd..a743f86 100644
--- a/lib/App/NetdiscoX/Util/ACI.pm
+++ b/lib/App/NetdiscoX/Util/ACI.pm
@@ -12,7 +12,7 @@ use URL::Encode ':all';
 use Hash::Merge qw(merge);
 use Moo;
 use namespace::clean;
-
+use Socket;
 
 has port => (
   is  => 'rw',
@@ -31,7 +31,7 @@ has [qw(host user password)] => (
 
 sub url {
   my $self = shift;
-  return "https://" . $self->{host} .  ":" . $self->{port} . "/api";
+  return "https://" . gethostbyaddr(inet_aton($self->{host}), 2) .  ":" . $self->{port} . "/api";
 }
 
 sub nodeinfo {
```

This of course required that the IP have a correct PTR in the DNS, but fixes the other issue. 
I wrote this instead of a direct pull request to try and explain my reasoning first :)

Maybe someone comes up with a better Idea.
Additional Suggestion: Mention HTTPS_CA_FILE Env variable (maybe even default it to /etc/ssl/certs/ca-certificates.crt) as correct way to add certificate in README.md. Other methods (at least under Ubuntu) seem to be entirely useless.

**Comment by rc9000** [comment]
Hi! I think this would be a good addition, but could you make it conditional? So that it tries the reverse lookup but if it fails it still uses the IP? Like this people are not forced to have DNS entries. 

Best is if you put it in a PR (maybe also with the HTTPS_CA_FILE, or as two separate PRs), then you get proper credits in your github profile.

**Comment by rc9000** [comment]
Hi @sjuerges, I was also encountering some issues with this in our latest setup. There is now a `https_hostname` in device_auth that allows to exactly specify the name that will be used in the API connection. It turns out between IPv6, CNAMES etc. people can get pretty creative so I thought just putting it there explicitly might be even better than a reverse lookup.

https://github.com/rc9000/nd2-worker-plugin-aci/commit/e9c48255fe33b8bea8297cdc94339f8e68f604a9
